### ISSUE TITLE
Project Task: Implement Algebraic Schematic Manipulation Engine

### ISSUE THREAD

**Issue by Kreijstal** [Kreijstal/circuijts#1]
**1. Overall Goal:**

Develop a rule-based engine within the `circuijts` package to algebraically simplify and transform circuit descriptions. The engine should operate on the circuit's graph representation and apply user-defined rules to achieve a simplified or canonical form. The system should be modular, allowing for easy addition and management of transformation rules.

**2. Core Objectives:**

*   **Extend Circuit Representation:** Modify the `circuijt` language, parser, AST, and graph representation to include component parameters (e.g., resistance value, capacitance value).
*   **Develop a Rule Definition Format:** Design and implement a clear, machine-parsable format for defining transformation rules (e.g., YAML or a Python-based DSL).
*   **Implement a Rule Engine:** Create a system that can load rules, match rule patterns against a circuit graph, and apply rule actions to transform the graph.
*   **Implement Initial Rule Set:** Provide a foundational set of simplification rules (e.g., series/parallel resistor combination, zero-ohm resistor removal).
*   **CLI Interface:** Create a CLI tool to apply these transformations to `.circuijt` files.
*   **Testing:** Ensure robust testing for all new components.

**3. Detailed Tasks & Deliverables:**

**Task 3.1: Extend Circuit Representation for Parameters**

*   **Description:**
    *   Modify the `spec.md` to define syntax for component parameters in declarations (e.g., `R R1 value=1k`, `C C1 value=1uF`).
    *   Update `circuijt/parser.py`:
        *   Modify `DECLARATION_RE` and parsing logic to extract component type, instance name, and a dictionary of parameters.
        *   Store parameters in the AST declaration nodes.
    *   Update `circuijt/ast_utils.py`:
        *   Ensure `generate_proto_from_ast` can reconstruct declarations with parameters.
    *   Update `circuijt/graph_utils.py`:
        *   When building the graph in `ast_to_graph`, store component parameters in the graph node data for component instances.
        *   Ensure `graph_to_structured_ast` preserves/reconstructs parameter information if possible (or notes its absence for behavioral components).
    *   Update `circuijt/components.py` (or create a new mechanism) if specific parameters are expected per component type for validation.
*   **Deliverables:**
    *   Updated `spec.md`.
    *   Modified Python files (`parser.py`, `ast_utils.py`, `graph_utils.py`).
    *   Unit tests for parsing declarations with parameters.
    *   Unit tests verifying parameters are correctly stored in the AST and graph.
    *   Example `.circuijt` files using the new parameter syntax.
*   **Testing Focus:**
    *   Parsing valid and invalid parameter syntax.
    *   Correct extraction of parameter names and values (strings initially, consider type conversion later).
    *   Round-trip consistency (parse -> AST -> graph -> AST -> text).

**Task 3.2: Design and Implement Rule Definition Format**

*   **Description:**
    *   Propose and document a format for defining transformation rules. Consider YAML or a Pythonic DSL.
        *   **LHS (Match Pattern):** How to specify subgraphs (nodes, types, connections, terminal involvement).
        *   **Conditions:** How to specify predicates on component parameters or graph topology (e.g., `R1.value > 0`, `degree(internal_net) == 2`).
        *   **RHS (Action/Replacement):** How to specify graph modifications (add/remove nodes/edges, update parameters, merge nets).
    *   Implement a parser for this rule format if it's not directly Python.
*   **Deliverables:**
    *   Documentation for the rule definition format (`rules_spec.md`).
    *   Python module (`circuijt/rules_parser.py` or similar) for loading/parsing rules.
    *   Example rule files in the chosen format.
*   **Testing Focus:**
    *   Parsing valid and invalid rule definitions.
    *   Correct interpretation of match patterns, conditions, and actions into internal data structures.

**Task 3.3: Implement the Rule Engine**

*   **Description:**
    *   Create `circuijt/rule_engine.py`.
    *   The engine should:
        *   Load a set of parsed rules.
        *   Take a circuit graph (and DSU) as input.
        *   Iteratively apply rules:
            *   Implement robust subgraph matching logic for rule LHS patterns. Consider using `networkx.isomorphism` for simple patterns or develop custom traversal for more complex/conditional matching.
            *   Implement condition checking.
            *   Implement graph modification logic based on rule RHS actions (adding/removing nodes/edges, updating DSU for net merges, modifying component node data for parameter changes).
        *   Manage the iteration process (e.g., repeat until no more rules apply, or for a fixed number of passes).
        *   Log applied rules and their effects.
*   **Deliverables:**
    *   `circuijt/rule_engine.py` with `RuleEngine` class and methods.
    *   Unit tests for the engine's core functionalities (matching, condition evaluation, graph modification, iteration control).
*   **Testing Focus:**
    *   Correctly matching simple subgraph patterns.
    *   Correctly evaluating conditions.
    *   Accurately performing graph modifications (node/edge addition/deletion, parameter updates).
    *   Termination of the rule application loop.
    *   Effect of rule application order (if relevant for initial simple rules).

**Task 3.4: Implement Initial Simplification Rule Set**

*   **Description:** Implement the following rules using the defined format and engine:
    1.  **Combine Series Resistors:** `R1 -- NetInternal -- R2` -> `R_eq` (if `NetInternal` has degree 2).
        *   `R_eq.value = R1.value + R2.value`.
    2.  **Combine Parallel Resistors:** `[R1 || R2]` -> `R_eq`.
        *   `R_eq.value = (R1.value * R2.value) / (R1.value + R2.value)`.
    3.  **Remove Zero-Ohm Resistor (Short Circuit):** Resistor with `value == 0` is replaced by a direct connection (merge its two nets).
    4.  **Remove Infinite-Ohm Resistor (Open Circuit):** Resistor with `value == infinity` (or a very large threshold) is removed.
    5.  *(Optional Bonus)*: Similar series/parallel rules for Capacitors and Inductors.
*   **Deliverables:**
    *   Rule definition files (e.g., `rules/simplification_rules.yaml`) for the implemented rules.
    *   Unit tests for each rule, verifying correct transformation on sample circuit snippets.
*   **Testing Focus:**
    *   Each rule applies correctly when its pattern and conditions are met.
    *   Each rule does *not* apply when patterns/conditions are not met.
    *   Correct calculation of new component parameters.
    *   Correct modification of graph topology (nets merged, components added/removed, connections rewired).

**Task 3.5: Create CLI for Transformations**

*   **Description:**
    *   Create a new CLI script `transform_circuit.py` (in the root `circuijts` directory).
    *   The CLI should:
        *   Take an input `.circuijt` file.
        *   Take an optional path to a rule file or rule set identifier.
        *   Parse the circuit, build the graph.
        *   Initialize and run the `RuleEngine` with the specified rules.
        *   Convert the transformed graph back to a `.circuijt` AST (using `graph_to_structured_ast` and then `generate_proto_from_ast`).
        *   Print the transformed circuit to stdout or save to an output file.
        *   Optionally, print a log of applied rules.
    *   Add a `make transform` target to `Makefile`.
*   **Deliverables:**
    *   `transform_circuit.py` script.
    *   Updated `Makefile`.
    *   End-to-end tests using example circuits and rule files, verifying the output circuit.
*   **Testing Focus:**
    *   CLI argument parsing.
    *   Correct loading of circuit and rules.
    *   Successful execution of the transformation pipeline.
    *   Legible output of transformed circuit and logs.

**4. General Development Guidelines:**

*   **Modularity:** Keep components (parser, graph utils, rule engine, rule definitions) as decoupled as possible.
*   **Clarity:** Code should be well-commented and easy to understand. Rule definitions should be human-readable.
*   **Testing:** Write comprehensive unit tests for all new logic. Test edge cases and invalid inputs.
*   **Documentation:** Update `README.md` and `spec.md` as new features are added. Document the rule definition format clearly.
*   **Version Control:** Use Git for version control, with frequent, atomic commits.

**5. Expected Output "Look and Feel":**

*   **Rule Definition (Example YAML):**
    ```yaml
    - rule_name: "CombineSeriesResistors"
      description: "Replaces two resistors R1, R2 in series with a single R_eq."
      match:
        # ... (pattern definition for two series resistors R1, R2 connected via NetB)
        # Example:
        # nodes:
        #   - {id: r1, type: R}
        #   - {id: r2, type: R}
        #   - {id: net_a}
        #   - {id: net_b} # Internal net
        #   - {id: net_c}
        # connections:
        #   - {from: net_a, to: r1, terminal_to: t1}
        #   - {from: r1, terminal_from: t2, to: net_b}
        #   - {from: net_b, to: r2, terminal_to: t1}
        #   - {from: r2, terminal_from: t2, to: net_c}
      conditions:
        # Example:
        # - "graph.degree(net_b) == 2" # net_b only connects r1 and r2
        # - "r1.parameters.value is not None"
        # - "r2.parameters.value is not None"
      actions:
        # Example:
        # remove_nodes: [r1, r2, net_b]
        # add_node: {id: r_eq, type: R, parameters: {value: "r1.parameters.value + r2.parameters.value"}}
        # add_edges:
        #   - {from: net_a, to: r_eq, terminal_to: t1}
        #   - {from: r_eq, terminal_from: t2, to: net_c}
    ```
*   **CLI Usage:**
    ```bash
    python transform_circuit.py circuits/my_complex_circuit.circuijt --rules rules/simplifications.yaml --output circuits/my_simplified_circuit.circuijt
    # Output:
    # Applying rule 'CombineSeriesResistors' to R1, R2 -> R_eq1
    # Applying rule 'RemoveZeroOhmResistor' to R_short
    # ...
    # Simplified circuit written to circuits/my_simplified_circuit.circuijt
    ```
*   **Transformed `.circuijt` file:** Should be a valid circuit description reflecting the changes.
